# Generated by Django 5.2.11 on 2026-03-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_photo_image_photo_storage_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
